{"name": "test_accept_order_twice_error", "status": "passed", "description": "Проверка невозможности принятия заказа, если его уже взяли в работу. Получаем код 409 и сообщение 'Этот заказ уже в работе'", "steps": [{"name": "Принять заказ и получить его id", "status": "passed", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "payload", "value": "'{\"firstName\": \"\\u0421\\u0438\\u043b\\u044c\\u0432\\u0435\\u0441\\u0442\\u0440\", \"lastName\": \"\\u041a\\u0438\\u0440\\u0438\\u043b\\u043b\\u043e\\u0432\\u0430\", \"address\": \"\\u0434. \\u041c\\u0430\\u043b\\u0433\\u043e\\u0431\\u0435\\u043a, \\u0430\\u043b\\u043b. \\u041b\\u0443\\u043d\\u043d\\u0430\\u044f, \\u0434. 2, 925569\", \"metroStation\": 1, \"phone\": \"8 663 526 0423\", \"rentTime\": 4, \"deliveryDate\": \"1985-05-07\", \"color\": \"BLACK\", \"comment\": \"\\u0422\\u0443\\u0442\\u0430.\"}'"}], "start": 1716397730081, "stop": 1716397730185}, {"name": "Получить заказ по его номеру", "status": "passed", "parameters": [{"name": "track_number", "value": "419783"}], "start": 1716397730185, "stop": 1716397730287}], "start": 1716397730052, "stop": 1716397730287}, {"name": "Создание и Логин курьера в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'kypyurifcs', 'password': 'ygungndvdg', 'firstName': 'xaikglxcxw'}"}], "start": 1716397730287, "stop": 1716397730435}, {"name": "Принять заказ", "status": "passed", "parameters": [{"name": "id_order", "value": "286116"}, {"name": "id_courier", "value": "312371"}], "start": 1716397730435, "stop": 1716397730534}, {"name": "Принять заказ", "status": "passed", "parameters": [{"name": "id_order", "value": "286116"}, {"name": "id_courier", "value": "312371"}], "start": 1716397730534, "stop": 1716397730605}], "start": 1716397730052, "stop": 1716397730606, "uuid": "1d8c62af-d07d-48e0-86c5-5d9c7c4fc8b4", "historyId": "25657ea45580c9f35f74fd7fe579c48e", "testCaseId": "25657ea45580c9f35f74fd7fe579c48e", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_twice_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-K"}, {"name": "thread", "value": "3168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}