{"name": "test_accept_order_twice_error", "status": "passed", "description": "Проверка невозможности принятия заказа, если его уже взяли в работу. Получаем код 409 и сообщение 'Этот заказ уже в работе'", "steps": [{"name": "Принять заказ и получить его id", "status": "passed", "steps": [{"name": "Создание заказа", "status": "passed", "parameters": [{"name": "payload", "value": "'{\"firstName\": \"\\u041a\\u043e\\u043d\\u0434\\u0440\\u0430\\u0442\", \"lastName\": \"\\u0413\\u043e\\u043b\\u0443\\u0431\\u0435\\u0432\\u0430\", \"address\": \"\\u043a\\u043b\\u0445 \\u041c\\u044b\\u0441 \\u0428\\u043c\\u0438\\u0434\\u0442\\u0430, \\u043f\\u0435\\u0440. \\u0411\\u0430\\u0437\\u0430\\u0440\\u043d\\u044b\\u0439, \\u0434. 12, 012934\", \"metroStation\": 0, \"phone\": \"8 (581) 302-21-71\", \"rentTime\": 2, \"deliveryDate\": \"1991-11-11\", \"color\": \"BLACK\", \"comment\": \"\\u0411\\u0435\\u0442\\u043e\\u043d\\u043d\\u044b\\u0439.\"}'"}], "start": 1716822762299, "stop": 1716822762403}, {"name": "Получить заказ по его номеру", "status": "passed", "parameters": [{"name": "track_number", "value": "804525"}], "start": 1716822762403, "stop": 1716822762501}], "start": 1716822762269, "stop": 1716822762502}, {"name": "Создание и Логин курьера в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'fzrzxemjhf', 'password': 'bzljpkuwjh', 'firstName': 'hlosghwgsa'}"}], "start": 1716822762502, "stop": 1716822762697}, {"name": "Принять заказ", "status": "passed", "parameters": [{"name": "id_order", "value": "288714"}, {"name": "id_courier", "value": "315213"}], "start": 1716822762697, "stop": 1716822762813}, {"name": "Принять заказ", "status": "passed", "parameters": [{"name": "id_order", "value": "288714"}, {"name": "id_courier", "value": "315213"}], "start": 1716822762813, "stop": 1716822762882}], "start": 1716822762269, "stop": 1716822762883, "uuid": "15c6a064-8693-4ecb-880b-b7dfe1199177", "historyId": "25657ea45580c9f35f74fd7fe579c48e", "testCaseId": "25657ea45580c9f35f74fd7fe579c48e", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_twice_error", "labels": [{"name": "suite", "value": "Ручка /api/v1/orders/"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-K"}, {"name": "thread", "value": "11960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}