{"name": "test_no_such_login", "status": "passed", "description": "Проверка невозможности залогиниться с несуществующим аккаунтом. Получаем ошибку 404", "steps": [{"name": "Логин курьера в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'fdhinjxvqx', 'password': 'ntkllkssxo', 'firstName': 'fenkdwpymn'}"}], "start": 1716397757215, "stop": 1716397757271}], "start": 1716397757215, "stop": 1716397757271, "uuid": "61e047ac-702b-46e7-8858-084a370c7dfd", "historyId": "f8ba477e2ecf698f789d7f765c2b2fc5", "testCaseId": "f8ba477e2ecf698f789d7f765c2b2fc5", "fullName": "tests.test_login_courier.TestLoginCourier#test_no_such_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-K"}, {"name": "thread", "value": "3168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}